name: architecture_template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1


environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

 

  #core
  equatable: ^2.0.5

  #navitagion
  auto_route: ^7.8.4

  #network dependencies
  vexana: ^4.0.3
  native_dio_adapter: ^1.3.0

  #state
  flutter_riverpod: ^2.4.10

  #Config
 
  json_annotation: ^4.8.1
  easy_localization: ^3.0.4






  #Utility
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  kartal: ^3.5.0


# Modules
 
  common:
    path: module/common
  core:
    path: module/core
  gen:
    path: module/gen
  widgets:
    path: module/widgets




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  flutter_launcher_icons: "^0.13.1"
  device_preview: ^1.1.0


  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true


  



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
 
  assets:
    - asset/translations/


  fonts:
    - family: Cereal
      fonts:
        - asset: asset/fonts/AirbnbCereal_W_Bd.otf
        - asset: asset/fonts/AirbnbCereal_W_Bk.otf
        - asset: asset/fonts/AirbnbCereal_W_Blk.otf
        - asset: asset/fonts/AirbnbCereal_W_Lt.otf
        - asset: asset/fonts/AirbnbCereal_W_Md.otf
        - asset: asset/fonts/AirbnbCereal_W_XBd.otf